apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres 
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgresSuperUserPsw
  POSTGRES_HOSTNAME: mypostgres
  POSTGRES_PORT: "5432"
  DATABASE_URL: postgresql://postgres:postgresSuperUserPsw@mypostgres:5432/postgres
