apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-app
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification-container
          # resources:
          #     requests:
          #       cpu: "500m"
          #     limits:
          #       cpu: "500m"
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/notification:latest
          command: ["/app/target/release/notification"]
          # command: ["sleep", "infinity"]
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: TELEGRAM_BOT_ID
              value: 6886711339:AAGtn-uPuu2dHi4Y4KmJF47ovymj4XCAes4
