apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: notification-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 65
