apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-app
  labels:
    app: healthcheck
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcheck
  template:
    metadata:
      labels:
        app: healthcheck
    spec:
      containers:
        - name: healthcheck-container
          # resources:
          #     requests:
          #       cpu: "500m"
          #     limits:
          #       cpu: "500m"
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/healthcheck:latest
          command: ["/app/target/release/healthcheck"]
          # command: ["sleep", "infinity"]
          envFrom:
            - configMapRef:
                name: postgres-config
      imagePullPolicy: Always
